
CMEXT_REQUIRE(Clang_LIBRARIES   "STI requires Clang_LIBRARIES")
CMEXT_REQUIRE(CAttrib_LIBRARIES "STI requires CAttrib_LIBRARIES")

CMEXT_ADD_FILE_DIR(STI sti/include)
CMEXT_ADD_FILE_DIR(STI sti/src)


SET(STI_LINK_LIBS 
	${Clang_LIBRARIES}
	${CAttrib_LIBRARIES}
	)
	

CMEXT_ADD_LIBRARY(STI STATIC)

#CMEXT_ADD_UNIT_TEST(STI sti-unit)

STATIC_LIB_NAME(STI)

SET(STI_INCLUDE_DIR ${${name}_ROOT_DIR_GLOBAL}/sti/include)
SET(STI_LIBRARIES   ${LIB_DIR}/${STI_STATIC_LIB_NAME})