
CMEXT_REQUIRE(CytokUtils_LIBRARIES     "STI requires CytokUtils_LIBRARIES")
CMEXT_REQUIRE(Clang_LIBRARIES          "STI requires Clang_LIBRARIES")
CMEXT_REQUIRE(CAttrib_LIBRARIES        "STI requires CAttrib_LIBRARIES")
CMEXT_REQUIRE(Boost_FOUND              "STI requires Boost_FOUND")

CMEXT_ADD_FILE_DIR(STI STI sti/include)
CMEXT_ADD_FILE_DIR(STI STI sti/src)


SET(STI_LINK_LIBS 
	${CytokUtils_LIBRARIES} 
	${Clang_LIBRARIES}
	${CAttrib_LIBRARIES}
	${Boost_LIBRARIES}
	)
	

CMEXT_ADD_LIBRARY(STI STI STATIC)

#CMEXT_ADD_UNIT_TEST(STI sti-unit)

STATIC_LIB_NAME(STI)

SET(STI_INCLUDE_DIR ${STI_ROOT_DIR_GLOBAL}/sti/include)
SET(STI_LIBRARIES   ${LIB_DIR}/${STI_STATIC_LIB_NAME})