
CMEXT_REQUIRE(Clang_LIBRARIES   "CES_Dev requires Clang_LIBRARIES")
CMEXT_REQUIRE(STI_LIBRARIES     "CES_Dev requires STI_LIBRARIES")
CMEXT_REQUIRE(CAttrib_LIBRARIES "CES_Dev requires CAttrib_LIBRARIES")
CMEXT_REQUIRE(Boost_FOUND       "CES_Dev requires Boost_FOUND")
CMEXT_REQUIRE(GTEST_FOUND	    "CES_Dev requires Google Test")

CMEXT_ADD_FILE_DIR(CES_DEV ces_dev)

SET(CES_DEV_LINK_LIBS 
	#${Clang_LIBRARIES}
	#${CAttrib_LIBRARIES}
	#${STI_LIBRARIES}
	${Boost_LIBRARIES}
	#${GTEST_BOTH_LIBRARIES}
	${LUA_LIBRARIES}
	)

CMEXT_ADD_EXECUTABLE(CES_DEV)
