
CMEXT_REQUIRE(Clang_LIBRARIES   "STI requires Clang_LIBRARIES")
CMEXT_REQUIRE(STI_LIBRARIES     "STI requires STI_LIBRARIES")
CMEXT_REQUIRE(CAttrib_LIBRARIES "STI requires CAttrib_LIBRARIES")
CMEXT_REQUIRE(Boost_FOUND       "STI requires Boost_FOUND")
CMEXT_REQUIRE(SWIG_FOUND		"STI requires SWIG_FOUND")
CMEXT_REQUIRE(RUBY_FOUND		"STI requires SWIG_FOUND")

CMEXT_ADD_FILE_DIR(STIG stig/include)
CMEXT_ADD_FILE_DIR(STIG stig/src)

SET(STIG_LINK_LIBS 
	${Clang_LIBRARIES}
	${CAttrib_LIBRARIES}
	${STI_LIBRARIES}
	${Boost_LIBRARIES}
	)

CMEXT_ADD_EXECUTABLE(STIG)

#CMEXT_ADD_UNIT_TEST(STIG stig-unit)

SET(STIG_INCLUDE_DIR ${STIG_ROOT_DIR_GLOBAL}/stig/include)
SET(STIG_LIBRARIES   ${LIB_DIR}/${STIG_STATIC_LIB_NAME})


SET(STIG_SWIG_FILES 
	${STIG_ROOT_DIR_GLOBAL}/stig/include/stig/Module3.swg
	)

## 
FOREACH(swig_file ${STIG_SWIG_FILES})
	SET_SOURCE_FILES_PROPERTIES(${swig_file} PROPERTIES CPLUSPLUS ON)
	SET_SOURCE_FILES_PROPERTIES(${swig_file} PROPERTIES SWIG_FLAGS "-includeall")
ENDFOREACH()

SWIG_ADD_MODULE(Module3 ruby 
	${STIG_ROOT_DIR_GLOBAL}/stig/include/stig/Module3.swg 
	${STIG_ROOT_DIR_GLOBAL}/stig/src/swig/Module3.cpp
	)

SWIG_LINK_LIBRARIES(Module3 ${RUBY_LIBRARY})

