
CMEXT_REQUIRE(CytokUtils_LIBRARIES     "STIG requires CytokUtils_LIBRARIES")
CMEXT_REQUIRE(Clang_LIBRARIES   	   "STIG requires Clang_LIBRARIES")
CMEXT_REQUIRE(STI_LIBRARIES     	   "STIG requires STI_LIBRARIES")
CMEXT_REQUIRE(CAttrib_LIBRARIES 	   "STIG requires CAttrib_LIBRARIES")
CMEXT_REQUIRE(Boost_FOUND       	   "STIG requires Boost_FOUND")
CMEXT_REQUIRE(GTEST_FOUND	           "STIG requires Google Test")

CMEXT_ADD_FILE_DIR(STIG STIG stig/include)
CMEXT_ADD_FILE_DIR(STIG STIG stig/src)

SET(STIG_LINK_LIBS 
	${CytokUtils_LIBRARIES}
	${Clang_LIBRARIES}
	${CAttrib_LIBRARIES}
	${STI_LIBRARIES}
	${Boost_LIBRARIES}
	${GTEST_BOTH_LIBRARIES}
	${LUA_LIBRARIES}
	)

CMEXT_ADD_EXECUTABLE(STIG STIG)


#CMEXT_ADD_UNIT_TEST(STIG stig-unit)

SET(STIG_INCLUDE_DIR ${STIG_ROOT_DIR_GLOBAL}/stig/include)
SET(STIG_LIBRARIES   ${LIB_DIR}/${STIG_STATIC_LIB_NAME} )


ADD_CUSTOM_TARGET(RunSWIG
    COMMAND ${SWIG_EXECUTABLE} -c++ -lua -o ${STIG_ROOT_DIR_GLOBAL}/stig/src/swig/CES_wrap.cpp ${STIG_ROOT_DIR_GLOBAL}/stig/include/stig/ces/CES.swg 
)

cmext_source_group(STIG stig)