
#define STIG_MAJOR_VERSION @VERSION_MAJOR@
#define STIG_MINOR_VERSION @VERSION_MINOR@
#define STIG_PATCH_VERSION @VERSION_PATCH@
#define STIG_COMMIT_VERSION "@VERSION_COMMIT@"
#define STIG_REVISION_VERSION @VERSION_REVISION@

#define STIG_VERSION_FULL "@VERSION_FULL@"
#define STIG_VERSION "@VERSION@"




